// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzLZ9YgjIapQ004obve8VWHXVlrQhNEMk',
    appId: '1:1023624968838:android:773bf34ed3aa7972e4af07',
    messagingSenderId: '1023624968838',
    projectId: 'electric-ecommerce',
    storageBucket: 'electric-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4DsR9h3AqEf2NYKpPV1mK5YbtFKw5Vi4',
    appId: '1:1023624968838:ios:bd733b8d76cf4d36e4af07',
    messagingSenderId: '1023624968838',
    projectId: 'electric-ecommerce',
    storageBucket: 'electric-ecommerce.appspot.com',
    iosBundleId: 'com.example.elctricEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQow_03fFzpCCLrBmX_BS9hSZZiZZ9pIk',
    appId: '1:1023624968838:web:5affc0f9992ce566e4af07',
    messagingSenderId: '1023624968838',
    projectId: 'electric-ecommerce',
    authDomain: 'electric-ecommerce.firebaseapp.com',
    storageBucket: 'electric-ecommerce.appspot.com',
  );
}
